export type Customer = {
  id: number;
  mkt_id: number;
  name: string;
  company: string;
  gender: string;
  phone_1: string;
  phone_2: string;
  phone_3: string;
  registration_number: string;
  code: string;
  email: string;
  billing_name: string;
  billing_phone: string;
  billing_country: string;
  billing_suburb: string;
  billing_city: string;
  billing_locality_id: string;
  billing_street: string;
  billing_postal_code: string;
  shipping_country: string;
  shipping_suburb: string;
  shipping_city: string;
  shipping_locality_id: string;
  shipping_postal_code: string;
  shipping_contact: string;
  shipping_phone: string;
  created: string;
  modified: string;
  bank: string;
  iban: string;
  legal_entity: number;
  fax: string | null;
  is_vat_payer: number;
  liable_person: string;
  shipping_street: string;
};
